### PR TITLE
fix indexing with sliced DimSelectors

### LINKED ISSUE #1189: selectors not dropped from DimSelectors after indexing
Noticed this because of the test failure in #1187 : when taking a slice from `DimSelectors`, the dimension is dropped, but the selector is not, which results in broken behaviour:

```
using DimensionalData
da = rand(X(1:10), Y(1:10))
xydimsel = DimSelectors(da; selectors = (At, Near))
ydimsel = xydimsel[X(1)]

da2 = rand(X(1:10), Y(1.1:10.1))
# works
da2[xydimsel]
# should work because selector is near, but errors
da2[ydimsel]

ydimsel.selectors # (At(), Near())
```

`_simplify_dim_indices` assumes the same number of selectors and dimensions:
https://github.com/rafaqz/DimensionalData.jl/blob/39f33a824033643589d9ee62ba09fb1c5e64da9c/src/array/indexing.jl#L200-L207

ERROR: SelectorError: attempt to select 1 from lookup Sampled{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ForwardOrdered, Regular{Float64}, Points, NoMetadata} with bounds (1.1, 10.1)

```
Stacktrace:
  [1] _selnotfound(l::Sampled{Float64, StepRangeLen{…}, ForwardOrdered, Regular{…}, Points, NoMetadata}, selval::Int64)
    @ DimensionalData.Dimensions.Lookups C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:242
  [2] _selnotfound_or_nothing(err::DimensionalData.Dimensions.Lookups._True, lookup::Sampled{…}, selval::Int64)
    @ DimensionalData.Dimensions.Lookups C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:240
  [3] at(::ForwardOrdered, ::Regular{…}, lookup::Sampled{…}, selval::Int64, atol::Nothing; err::DimensionalData.Dimensions.Lookups._True)
    @ DimensionalData.Dimensions.Lookups C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:207
  [4] at
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:195 [inlined]
  [5] #at#38
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:167 [inlined]
  [6] at
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:166 [inlined]
  [7] _selectindices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:1108 [inlined]
  [8] selectindices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:1084 [inlined]
  [9] selectindices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Lookups\selector.jl:1075 [inlined]
 [10] _dims2indices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:144 [inlined]
 [11] _dims2indices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:136 [inlined]
 [12] dims2indices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:31 [inlined]
 [13] macro expansion
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:89 [inlined]
 [14] split_alignments
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:89 [inlined]
 [15] split_alignments
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:87 [inlined]
 [16] dims2indices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:56 [inlined]
 [17] dims2indices
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\Dimensions\indexing.jl:32 [inlined]
 [18] _dim_getindex
    @ C:\Users\tsh371\.julia\dev\DimensionalData\src\array\indexing.jl:62 [inlined]
 [19] getindex(A::DimMatrix{…}, d1::DimSelectors{…})
    @ DimensionalData C:\Users\tsh371\.julia\dev\DimensionalData\src\array\indexing.jl:53
 [20] top-level scope
    @ c:\Users\tsh371\.julia\dev\DimensionalData\test\runtests.jl:8
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by tiemvanderdeure**
closes https://github.com/rafaqz/DimensionalData.jl/issues/1189

Now respects `selectors` passed to `DimSelectors`, even after slicing

### CODE REVIEW

File: src/array/indexing.jl [hunk 1]
```diff
@@ -198,7 +198,8 @@ Base.@assume_effects :foldable @inline _simplify_dim_indices(::Tuple{}) = ()
 Base.@assume_effects :foldable @inline _simplify_dim_indices(d::DimIndices, ds...) =
     (dims(d)..., _simplify_dim_indices(ds)...)
 Base.@assume_effects :foldable @inline function _simplify_dim_indices(d::DimSelectors, ds...)
-    seldims = map(dims(d), d.selectors) do d, s
+    sorteddims = dims((dims(d)..., _refdims_firsts(d)...), orderdims(d))
```
Comment (tiemvanderdeure) [inline src/array/indexing.jl:201]: This is quite similar to `eldims` https://github.com/rafaqz/DimensionalData.jl/blob/39f33a824033643589d9ee62ba09fb1c5e64da9c/src/dimindices.jl#L11

And a pattern in `rebuild_selectors` https://github.com/rafaqz/DimensionalData.jl/blob/39f33a824033643589d9ee62ba09fb1c5e64da9c/src/dimindices.jl#L307

So maybe worth making this an internal function?

Comment (rafaqz) [reply src/array/indexing.jl:201]: Not needed for this PR tho
