### PR TITLE
Breaking: add iterate and collect

### LINKED ISSUE #810: Operations that call `collect` or `iterate` fail on some RasterStacks
Here's a running example (from my mapzonal code):

Setup:

```julia
using Rasters

r1 = Raster(rand(X(1:10), Y(1:10)))
r2 = Raster(rand(dims(r1)...))

rs = RasterStack(r1, r2)

bool_cond_raster = r1 .> 0.5

mask_inds = view(Rasters.DD.DimIndices(bool_cond_raster), bool_cond_raster)

masked_stack = rs[mask_inds] # fine so far

```

Operations on a directly masked stack

```julia

masked_stack[1] # also fine

collect(masked_stack) # errors

identity.(masked_stack) # errors
sum(masked_stack) # somehow fine and correct?

# errors for anything that calls `collect
```
Operations on a `view`ed stack
```julia
# If I try to view,

viewed_stack = view(rs, mask_inds)

viewed_stack[1] # also fine

collect(viewed_stack) # also errors

sum(viewed_stack) # also fine and correct

```

The error:

```julia

ERROR: Use iterate(layers(s)) rather than `iterate(s)`
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] iterate(::RasterStack{…})
   @ DimensionalData ~/.julia/dev/DimensionalData/src/stack/stack.jl:169
 [3] copyto!(dest::Vector{…}, src::RasterStack{…})
   @ Base ./abstractarray.jl:943
 [4] _collect(cont::UnitRange{…}, itr::RasterStack{…}, ::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:765
 [5] collect(itr::RasterStack{…})
   @ Base ./array.jl:759
 [6] broadcastable(x::RasterStack{…})
   @ Base.Broadcast ./broadcast.jl:743
 [7] broadcasted(::typeof(identity), ::RasterStack{…})
   @ Base.Broadcast ./broadcast.jl:1339
 [8] top-level scope
   @ REPL[99]:1
Some type information was truncated. Use `show(err)` to see complete types.

```1

### PR DESCRIPTION
**Pull request by rafaqz**
@asinghvi17 this should do what you want

Closes  #810

```julia
using DimensionalData
A = [1.0 2.0 3.0;
     4.0 5.0 6.0]
x, y, z = X([:a, :b]), Y(10.0:10.0:30.0; metadata=Dict()), Z()
dimz = x, y
da1 = DimArray(A, (x, y); name=:one, metadata=Metadata())
da2 = DimArray(Float32.(2A), (x, y); name=:two)
da3 = DimArray(Int.(3A), (x, y); name=:three)
da4 = DimArray(cat(4A, 5A, 6A, 7A; dims=3), (x, y, z); name=:extradim)

s = DimStack((da1, da2, da3))
mixed = DimStack(da1, da2, da4)
``` 

```julia
julia> [x for x in mixed]
╭──────────────────────────────────────────────────────────────────────────────╮
│ 2×3×4 DimArray{@NamedTuple{one::Float64, two::Float32, extradim::Float64},3} │
├──────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────── dims ┐
  ↓ X Categorical{Symbol} [:a, :b] ForwardOrdered,
  → Y Sampled{Float64} 10.0:10.0:30.0 ForwardOrdered Regular Points,
  ↗ Z
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[:, :, 1]
 ↓ →  10.0                                       20.0                                        30.0
  :a    (one = 1.0, two = 2.0, extradim = 4.0)     (one = 2.0, two = 4.0, extradim = 8.0)      (one = 3.0, two = 6.0, extradim = 12.0)
  :b    (one = 4.0, two = 8.0, extradim = 16.0)    (one = 5.0, two = 10.0, extradim = 20.0)    (one = 6.0, two = 12.0, extradim = 24.0)

julia> collect(mixed)
2×3×4 Array{@NamedTuple{one::Float64, two::Float32, extradim::Float64}, 3}:
[:, :, 1] =
 (one = 1.0, two = 2.0, extradim = 4.0)   (one = 2.0, two = 4.0, extradim = 8.0)    (one = 3.0, two = 6.0, extradim = 12.0)
 (one = 4.0, two = 8.0, extradim = 16.0)  (one = 5.0, two = 10.0, extradim = 20.0)  (one = 6.0, two = 12.0, extradim = 24.0)

[:, :, 2] =
 (one = 1.0, two = 2.0, extradim = 5.0)   (one = 2.0, two = 4.0, extradim = 10.0)   (one = 3.0, two = 6.0, extradim = 15.0)
 (one = 4.0, two = 8.0, extradim = 20.0)  (one = 5.0, two = 10.0, extradim = 25.0)  (one = 6.0, two = 12.0, extradim = 30.0)

[:, :, 3] =
 (one = 1.0, two = 2.0, extradim = 6.0)   (one = 2.0, two = 4.0, extradim = 12.0)   (one = 3.0, two = 6.0, extradim = 18.0)
 (one = 4.0, two = 8.0, extradim = 24.0)  (one = 5.0, two = 10.0, extradim = 30.0)  (one = 6.0, two = 12.0, extradim = 36.0)

[:, :, 4] =
 (one = 1.0, two = 2.0, extradim = 7.0)   (one = 2.0, two = 4.0, extradim = 14.0)   (one = 3.0, two = 6.0, extradim = 21.0)
 (one = 4.0, two = 8.0, extradim = 28.0)  (one = 5.0, two = 10.0, extradim = 35.0)  (one = 6.0, two = 12.0, extradim = 42.0)

julia> vec(mixed) # row table!
24-element Vector{@NamedTuple{one::Float64, two::Float32, extradim::Float64}}:
 (one = 1.0, two = 2.0, extradim = 4.0)
 (one = 4.0, two = 8.0, extradim = 16.0)
 (one = 2.0, two = 4.0, extradim = 8.0)
 (one = 5.0, two = 10.0, extradim = 20.0)
 (one = 3.0, two = 6.0, extradim = 12.0)
 (one = 6.0, two = 12.0, extradim = 24.0)
 (one = 1.0, two = 2.0, extradim = 5.0)
 (one = 4.0, two = 8.0, extradim = 20.0)
 (one = 2.0, two = 4.0, extradim = 10.0)
 (one = 5.0, two = 10.0, extradim = 25.0)
 (one = 3.0, two = 6.0, extradim = 15.0)
 ⋮
 (one = 4.0, two = 8.0, extradim = 24.0)
 (one = 2.0, two = 4.0, extradim = 12.0)
 (one = 5.0, two = 10.0, extradim = 30.0)
 (one = 3.0, two = 6.0, extradim = 18.0)
 (one = 6.0, two = 12.0, extradim = 36.0)
 (one = 1.0, two = 2.0, extradim = 7.0)
 (one = 4.0, two = 8.0, extradim = 28.0)
 (one = 2.0, two = 4.0, extradim = 14.0)
 (one = 5.0, two = 10.0, extradim = 35.0)
 (one = 3.0, two = 6.0, extradim = 21.0)
 (one = 6.0, two = 12.0, extradim = 42.0)
```

### CODE REVIEW

**Comment by rafaqz** [comment]
The weirdest thing about this is you still splat _layers_ into a `NamedTuple` rather than values. 

Into a `Tuple` you splat values. 

The Array/NamedTuple duality thing that `AbstractDimStack` is always creates some weirdness at the boundary, its just which weirdness is the most useful. Splatting values into a `NamedTuple` is never useful but spatting layers is really useful. But its still weird.

File: src/stack/stack.jl [hunk 1]
```diff
@@ -29,6 +29,9 @@ abstract type AbstractDimStack{K,T,N,L} end
 const AbstractVectorDimStack = AbstractDimStack{K,T,1} where {K,T}
 const AbstractMatrixDimStack = AbstractDimStack{K,T,2} where {K,T}
 
+(::Type{T})(st::AbstractDimStack) where T<:AbstractDimArray =
+    T([st[D] for D in DimIndices(st)]; dims=dims(st), metadata=metadata(st))
```
Comment (asinghvi17) [inline src/stack/stack.jl:33]: Does this mean that `Raster(RasterStack(...))` is actually an expensive operation / materializes everything in memory?  Is there a way we could avoid this, maybe a `ConcatDimArray` or something?

File: src/stack/stack.jl [hunk 2]
```diff
@@ -161,12 +165,15 @@ Base.checkbounds(T::Type, s::AbstractDimStack, I...) = checkbounds(T, CartesianI
...
 Base.NamedTuple(s::AbstractDimStack) = NamedTuple(layers(s))
-
-# Remove these, but explain
-Base.iterate(::AbstractDimStack, args...) = error("Use iterate(layers(s)) rather than `iterate(s)`") #iterate(layers(s), args...)
+Base.collect(st::AbstractDimStack) = parent([st[D] for D in DimIndices(st)])
+Base.Array(st::AbstractDimStack) = collect(st)
+Base.vec(st::AbstractDimStack) = vec(collect(st))
+@propagate_inbounds Base.iterate(st::AbstractDimStack) = iterate(st, 1)
+@propagate_inbounds Base.iterate(st::AbstractDimStack, i) = 
+    i > length(st) ? nothing : (st[DimIndices(st)[i]], i + 1)
```
Comment (asinghvi17) [inline src/stack/stack.jl:176]: Any way to hold off on re-instantiating the DimIndices object every time?  Indexing with linear indices (single integers) currently does what I want anyway, it just needs to be forwarded correctly?

File: src/stack/stack.jl [hunk 3]
```diff
@@ -195,8 +202,12 @@ function Base.merge(
     merge(map(layers, (x1, x2, x3, xs...))...)
 end
 
-Base.map(f, s::AbstractDimStack) = _maybestack(s,map(f, values(s)))
-function Base.map(
+Base.map(f, s::AbstractDimStack) = error("Use maplayers(f, stack)) instad of map(f, stack)")
+Base.map(f, ::Union{AbstractDimStack,NamedTuple}, xs::Union{AbstractDimStack,NamedTuple}...) =
+    error("Use maplayers(f, stack, args...)) instad of map(f, stack, args...)")
```
Comment (asinghvi17) [inline src/stack/stack.jl:207]: I guess this is the cost...but should it be?  Arguably if you expected `iterate` to work the way it will now, you also expected `map` to work that way...

Is it a common usage pattern to do eg `map(stack) do array`?

**Review by asinghvi17 — COMMENTED** [review]
Thanks!  Added some comments - not sure how you intend the API to work.  I should be able to push my code as it is tomorrow, that will be a better example of the usecase.

File: src/stack/stack.jl (hunk 1 above)
Comment (rafaqz) [reply src/stack/stack.jl:33]: Yeah in this implementation. `UnstackedDimArray` or `InterleavedDimArray` might be a better name because its really interleaving the layers not concatenating. 

I've also been thinking of just making `AbstractDimStack` an `AbstractArray` itself which would make that a moot point. This PR is a step in that direction.

File: src/stack/stack.jl (hunk 2 above)
Comment (rafaqz) [reply src/stack/stack.jl:176]: It should be free anyway. And if you index with linear indices it has to do DimIndices(A)[i] internally anyway!

Mixed dimension stacks indexing really works properly now because of Dimension indexing is used internally.

File: src/stack/stack.jl (hunk 3 above)
Comment (rafaqz) [reply src/stack/stack.jl:207]: Yeah, I've meant to deprecate this for ages anyway. The worse cost is how different splatting to a Tuple and a NamedTuple is.

Its a common pattern, but `maplayers` should be fine to use for it.

File: src/stack/stack.jl (hunk 1 above)
Comment (rafaqz) [reply src/stack/stack.jl:33]: For now lets just make it expensive
