### PR TITLE
Document Contains for Categoricals more clearly

### LINKED ISSUE #532: Contains for categorical Dimensions should call Base.contains on the Strings
I am surprised, that the Contains selector for Categorical values does call At and does not call the contains function.
My use case is, that I have a long  Variable dimensions with many different named variables for which some are similar or following a certain naming pattern.
And then I want to select a certain variable group like in this shortened example.
I would expect that the `Contains(value)` selector behaves as calling `Where(contains(value))`
I can open a PR with these changes, but I might need some help in making the Vector case work.

```
julia> arr = DimArray(rand(10,10,4), (X(1:10), Y(1:10), Dim{:Variable}(["root_moisture", "soil_moisture", "air_temperature", "something"])))
10×10×4 DimArray{Float64,3} with dimensions: 
  X Sampled{Int64} 1:10 ForwardOrdered Regular Points,
  Y Sampled{Int64} 1:10 ForwardOrdered Regular Points,
  Dim{:Variable} Categorical{String} String["root_moisture", "soil_moisture", "air_temperature", "something"] Unordered
[:, :, 1]
     1          2          3         4         5         6         7           8          9         10
  1  0.0451999  0.721679   0.472552  0.172361  0.838639  0.748815  0.00979697  0.0228791  0.312279   0.254207
  ⋮                                            ⋮                                                     ⋮
 10  0.0962899  0.0916193  0.856692  0.725752  0.530497  0.891864  0.307378    0.40408    0.429365   0.0391044
[and 3 more slices...]
julia> arr[Variable=Where(contains("moisture"))]
10×10×2 DimArray{Float64,3} with dimensions: 
  X Sampled{Int64} 1:10 ForwardOrdered Regular Points,
  Y Sampled{Int64} 1:10 ForwardOrdered Regular Points,
  Dim{:Variable} Categorical{String} String["root_moisture", "soil_moisture"] Unordered
[:, :, 1]
     1          2          3         4         5         6         7           8          9         10
  1  0.0451999  0.721679   0.472552  0.172361  0.838639  0.748815  0.00979697  0.0228791  0.312279   0.254207
  ⋮                                            ⋮                                                     ⋮
 10  0.0962899  0.0916193  0.856692  0.725752  0.530497  0.891864  0.307378    0.40408    0.429365   0.0391044
[and 1 more slices...]
julia> arr[Variable=Contains("moisture")] # This fails
ERROR: ArgumentError: moisture not found in ["root_moisture", "soil_moisture", "air_temperature", "something"]
Stacktrace:
```

### PR DESCRIPTION
**Pull request by felixcremer**
This would close #532 
I am still wondering, whether we should give an error for Categorical{String} dimensions.

### CODE REVIEW

**Comment by rafaqz** [comment]
Calling `At` also happens on points. The idea is that for values without an interbal,  containing a value us the sane as being equal to it

**Comment by rafaqz** [comment]
Calling `At` also happens on points. The idea is that for values without an interbal,  containing a value us the same as being equal to it

**Comment by felixcremer** [comment]
But I get an error when I run Contains on a Point dimension:

```julia
julia> arr = DimArray(rand(10,10,4), (X(1:10), Y(1:10), Dim{:Variable}(["root_moisture", "soil_moisture", "air_temperature", "something"])))
julia> arr[X=Contains(1)]
ERROR: ArgumentError: Points LookupArray cannot use `Contains`, use `Near` or `At` for Points.
Stacktrace:
  [1] contains(::DimensionalData.Dimensions.LookupArrays.Points, l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64}; err::DimensionalData.Dimensions.LookupArrays._True)
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:299
  [2] contains(::DimensionalData.Dimensions.LookupArrays.Points, l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64})
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:297
  [3] contains(l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:291
  [4] contains(l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64})
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:291
  [5] selectindices(l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:283
  [6] selectindices(l::DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, sel::Contains{Int64})
    @ DimensionalData.Dimensions.LookupArrays ~/.julia/dev/DimensionalData/src/LookupArrays/selector.jl:283
  [7] _dims2indices
    @ ~/.julia/dev/DimensionalData/src/Dimensions/indexing.jl:114 [inlined]
  [8] macro expansion
    @ ~/.julia/dev/DimensionalData/src/Dimensions/indexing.jl:56 [inlined]
  [9] _dims2indices(lookups::Tuple{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, DimensionalData.Dimensions.LookupArrays.Categorical{String, Vector{String}, DimensionalData.Dimensions.LookupArrays.Unordered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, dims::Tuple{X{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Dim{:Variable, DimensionalData.Dimensions.LookupArrays.Categorical{String, Vector{String}, DimensionalData.Dimensions.LookupArrays.Unordered, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, I::Tuple{X{Contains{Int64}}, Nothing, Nothing})
    @ DimensionalData.Dimensions ~/.julia/dev/DimensionalData/src/Dimensions/indexing.jl:56
 [10] dims2indices
    @ ~/.julia/dev/DimensionalData/src/Dimensions/indexing.jl:51 [inlined]
 [11] dims2indices
    @ ~/.julia/dev/DimensionalData/src/Dimensions/indexing.jl:34 [inlined]
 [12] #getindex#39
    @ ~/.julia/dev/DimensionalData/src/array/indexing.jl:49 [inlined]
 [13] top-level scope
    @ REPL[36]:1
```

**Comment by rafaqz** [comment]
Haha well thats totally inconsistent then, I think it has to do one or the other.

**Comment by rafaqz** [comment]
Making this fail on `Categorical` is breaking, if we want that we should get it in on the current breaking release. Otherwise we should make this work on `Points`

File: src/LookupArrays/selector.jl [hunk 1]
```diff
@@ -255,6 +267,8 @@ Selector that selects the interval the value is contained by. If the
 interval is not present in the index, an error will be thrown.
 
 Can only be used for [`Intervals`](@ref) or [`Categorical`](@ref).
+For [`Categorical`](@ref) it falls back to using [`At`](@ref).
+Use `Where(contains(x))` to check for containment in the categorical values.
```
Comment (rafaqz) [inline src/LookupArrays/selector.jl:271]:
```suggestion
`Contains` should not be confused with `Base.contains` - use `Where(contains(x))` to check for if values are contain in categorical values like strings.
```
