### PR TITLE
fix makie axis keywords

### LINKED ISSUE #929: Plot recipes are still eating `axis` kwargs
```julia
using Makie, Rasters
r1 = Raster(rand(X(10), Y(10))
heatmap(r1; axis = (; title = "Your title"))
```
the title doesn't show up

### PR DESCRIPTION
**Pull request by rafaqz**
Remove a bunch of complexity and makes `axis=(; title="foo")` and similar work.

Closes #929

(at the same time I renamed colorbarkw to colorbar to match the other keywords like axis. the previous colorbarkw will still work but is no longer documented)

### CODE REVIEW

File: ext/DimensionalDataMakie.jl [hunk 1]
```diff
@@ -71,10 +71,9 @@ for (f1, f2) in _paired(:plot => :scatter, :scatter, :lines, :scatterlines, :sta
     """
     @eval begin
         @doc $docstring
-        function Makie.$f1(A::AbstractDimVector; axislegendkw=(;), axis = (;), figure = (;), attributes...)
-            args, merged_attributes = _pointbased1(A, attributes)
-            axis_kw, figure_kw = _handle_axis_figure_attrs(merged_attributes, axis, figure)
-            p = Makie.$f2(args...; axis = axis_kw, figure = figure_kw, merged_attributes...)
+        function Makie.$f1(A::AbstractDimVector; axislegendkw=(;), axis=(;), attributes...)
```
Comment (asinghvi17) [inline ext/DimensionalDataMakie.jl:74]: might also do the same thing for axislegendkw

**Review by asinghvi17 — COMMENTED** [review]
No particular comments other than this one

File: ext/DimensionalDataMakie.jl (hunk 1 above)
Comment (rafaqz) [reply ext/DimensionalDataMakie.jl:74]: ahh I only got half way with that one
