### PR TITLE
Dimstack constructor fixes

### LINKED ISSUE #987: DimStack(data; name) does not work
Passing kw `name` to DimStack throws an error

create data
```julia
using DimensionalData
dX = X(collect(1:1000))
dY = Y(collect(1:1000))
varname = ["aa", "bb", "cc"]

das = [zeros(dX, dY) for v in varname]
```

place into a DimStack
```julia
DimStack(das; name=varname)
```

throws this error
```
ERROR: MethodError: no method matching DimStack(::Vector{DimMatrix{…}}; name::Vector{String})
This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.

Closest candidates are:
  DimStack(::AbstractArray{<:AbstractDimArray}; metadata, refdims) got unsupported keyword argument "name"
   @ DimensionalData ~/.julia/packages/DimensionalData/omXy6/src/stack/stack.jl:411
  DimStack(::Any, ::Any, ::Any, ::LD, ::Any, ::Any) where {K, LD<:(NamedTuple{K})} got unsupported keyword argument "name"
   @ DimensionalData ~/.julia/packages/DimensionalData/omXy6/src/stack/stack.jl:396
  DimStack(::AbstractDimArray; layersfrom, metadata, refdims, kw...)
   @ DimensionalData ~/.julia/packages/DimensionalData/omXy6/src/stack/stack.jl:424
  ...
```

### LINKED ISSUE #988: DimStack `keyword arguments` are undocumented
There is no documentation for DimStack `keyword arguments`

https://rafaqz.github.io/DimensionalData.jl/stable/api/reference#DimensionalData.DimStack

### PR DESCRIPTION
**Pull request by rafaqz**
Closes #987 and closes #988

### CODE REVIEW

File: src/stack/stack.jl [hunk 1]
```diff
@@ -307,24 +307,45 @@ end
...
-    This has very good performance, and avoids the need to always use `map`.
 - `getindex` or `view` with a `Vector` or `Colon` will return another `DimStack` where
     all data layers have been sliced.
 - `setindex!` must pass a `Tuple` or `NamedTuple` matching the layers.
-- many base and `Statistics` methods (`sum`, `mean` etc) will work as for a `DimArray`
-    again removing the need to use `map`.
+- many base and `Statistics` methods (`sum`, `mean` etc) will work as for a `DimArray`,
+    applied to all layers separately.
+- `map` and iteration apply as with getindex.
+- `maplayers` applies over array layers, as indexed with a `Symbol`.
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:347]:
```suggestion
- to apply a function to each layer of a `DimStack`, use [`maplayers`](@ref).
```

File: src/stack/stack.jl [hunk 2]
```diff
@@ -307,24 +307,45 @@ end
...
+- `refdims`: `NamedTuple` of `Dimension`s for each layer, `()` by default.
+
+## Details
+
+`DimStack` behaviour lies somewhere between a `DimArray` and a `NamedTuple`:
+
+- indexing with a `Symbol` as in `dimstack[:layername]` or using `getproperty` 
+    `dimstack.layername` returns a `DimArray` layer.
 - `getindex` or `view` with `Int`, `Dimension`s or `Selector`s that resolve to `Int` will
     return a `NamedTuple` of values from each layer in the stack.
```
[the remark this answers is not in the document]
Comment (tiemvanderdeure) [reply src/stack/stack.jl:340]: A `view` always returns a slice so this wasn't totally true.

File: src/stack/stack.jl [hunk 3]
```diff
@@ -307,24 +307,45 @@ end
...
-    This has very good performance, and avoids the need to always use `map`.
 - `getindex` or `view` with a `Vector` or `Colon` will return another `DimStack` where
     all data layers have been sliced.
 - `setindex!` must pass a `Tuple` or `NamedTuple` matching the layers.
-- many base and `Statistics` methods (`sum`, `mean` etc) will work as for a `DimArray`
-    again removing the need to use `map`.
+- many base and `Statistics` methods (`sum`, `mean` etc) will work as for a `DimArray`,
+    applied to all layers separately.
+- `map` and iteration apply as with getindex.
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:346]:
```suggestion
```
We can leave this out if we specify above

File: src/stack/stack.jl [hunk 4]
```diff
@@ -307,24 +307,45 @@ end
...
+
+`DimStack` behaviour lies somewhere between a `DimArray` and a `NamedTuple`:
+
+- indexing with a `Symbol` as in `dimstack[:layername]` or using `getproperty` 
+    `dimstack.layername` returns a `DimArray` layer.
 - `getindex` or `view` with `Int`, `Dimension`s or `Selector`s that resolve to `Int` will
     return a `NamedTuple` of values from each layer in the stack.
-    This has very good performance, and avoids the need to always use `map`.
 - `getindex` or `view` with a `Vector` or `Colon` will return another `DimStack` where
     all data layers have been sliced.
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:342]:
```suggestion
- `getindex` or `view` with a `Vector` or `Colon` will return another `DimStack` where
    all data layers have been sliced, unless this resolves to a single element, in which case 
    `getindex` returns a `NamedTuple`
```
Still a bit clunky maybe

File: src/stack/stack.jl [hunk 5]
```diff
@@ -392,66 +413,102 @@ struct DimStack{K,T,N,L,D<:Tuple,R<:Tuple,LD,M,LM} <: AbstractDimStack{K,T,N,L}
...
 )
-    keys_vec = uniquekeys(das)
-    keys_tuple = ntuple(i -> keys_vec[i], length(keys_vec))
-    dims = DD.combinedims(collect(das))
-    as = map(parent, das)
-    data = NamedTuple{keys_tuple}(as)
-    layerdims = NamedTuple{keys_tuple}(map(basedims, das))
-    layermetadata = NamedTuple{keys_tuple}(map(DD.metadata, das))
+    dims = DD.combinedims(das)
+    name_tuple = ntuple(i -> name[i], length(name))
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:436]: is this really preferred over just calling `Tuple`?

File: src/stack/stack.jl [hunk 6]
```diff
@@ -307,24 +307,45 @@ end
...
 
-- indexing with a `Symbol` as in `dimstack[:symbol]` returns a `DimArray` layer.
-- iteration and `map` apply over array layers, as indexed with a `Symbol`.
+- `data`: `AbstractDimArray` or an `AbstractArray`, `Tuple` or `NamedTuple` of `AbstractDimArray`s or `AbstractArray`s.
+- `dims`: `DimTuple` of `Dimension`s. Required when `data` is not `AbstractDimArray`s.
+
+## Keywords
+
+- `name`: `Array` `Tuple` of `Symbol` names for each layer. By default
+    the names of `DimArrays` are used, or `:layer1`, `:layer2`, etc.
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:322]:
```suggestion
- `name`: `Array` or `Tuple` of `Symbol` names for each layer. By default
    the names of `DimArrays` are or keys of a `NamedTuple` are used, 
    or `:layer1`, `:layer2`, etc.
```
We could also consider just requiring this to be Tuple of Symbol imo.

File: src/stack/stack.jl [hunk 7]
```diff
@@ -307,24 +307,45 @@ end
     DimStack <: AbstractDimStack
 
     DimStack(data::AbstractDimArray...; kw...)
-    DimStack(data::Tuple{Vararg{AbstractDimArray}}; kw...)
-    DimStack(data::NamedTuple{Keys,Vararg{AbstractDimArray}}; kw...)
-    DimStack(data::NamedTuple, dims::DimTuple; metadata=NoMetadata(); kw...)
+    DimStack(data::Union{AbstractArray,Tuple,NamedTuple}[, dims::DimTuple]; kw...)
```
Comment (tiemvanderdeure) [inline src/stack/stack.jl:310]:
```suggestion
    DimStack(data::Union{AbstractArray,Tuple,NamedTuple}, [dims::DimTuple]; kw...)
    DimStack(data::AbstractDimArray; layersfrom, kw...)
```

File: src/stack/stack.jl (hunk 6 above)
Comment (tiemvanderdeure) [reply src/stack/stack.jl:322]: Especially as passing a Vector of names isn't untested at the moment.

Comment (rafaqz) [reply src/stack/stack.jl:322]: A vector is useful when there is 300 of them

File: src/stack/stack.jl (hunk 5 above)
Comment (rafaqz) [reply src/stack/stack.jl:436]: When the length is known for an array yes,but now it's not
