### PR TITLE
Fix #263

### LINKED ISSUE #263: "No dims found" when operating on mean/ selecting dims by keyword with CoordMode coordinates.
MWE:
```
using DimensionalData, StaticArrays, Random

c = [rand(SVector{2, Float64}) for i in 1:100]
t = 0:0.1:10

d = (Coord(c, (DimensionalData.X, DimensionalData.Y)), Ti(t))
a = rand(length.(d)...)

A = DimArray(a, d)

B = mean(A; dims = Coord)
```
```
ERROR: No dims found
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] dims(#unused#::Nothing)
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\dimension.jl:172
  [3] _reducedims (repeats 3 times)
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:413 [inlined]
  [4] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:412 [inlined]
  [5] _reducedims(dim::Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, #unused#::Type{Coord})
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:421
  [6] map(f::typeof(DimensionalData._reducedims), t::Tuple{Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, Ti{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}, NoMetadata}}, s::Tuple{UnionAll, Nothing})      
    @ Base .\tuple.jl:233
  [7] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:414 [inlined]
  [8] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:413 [inlined]
  [9] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:412 [inlined]
 [10] reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:410 [inlined]
 [11] _mean(A::DimArray{Float64, 2, Tuple{Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, Ti{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}, NoMetadata}}, Tuple{}, Matrix{Float64}, NoName, NoMetadata}, dims::Type; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:21
 [12] _mean
    @ ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:21 [inlined]
 [13] #mean#238
    @ ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:16 [inlined]
 [14] top-level scope
    @ ~\Desktop\mwe.jl:11
 [15] eval
    @ .\boot.jl:360 [inlined]
```

This falls down to the function:
```
DimensionalData.reducedims(A, Coord)
```

As this is currently a completely stopper of my workflow, any tip on a quick fix would be super-duper appreciated :(

### PR DESCRIPTION
**Pull request by Datseris**
Fixes #263

### CODE REVIEW

File: src/coord.jl [hunk 1]
```diff
@@ -24,13 +24,19 @@ Coord(val::T=:) where T = Coord{T,AutoMode,NoMetadata}(val, AutoMode(), NoMetada
...
 sel2indices(dim::Coord, sel::StandardIndices) = sel
 
-_matches(sel::Dimension, x) = _matches(val(sel), x) 
+_matches(sel::Dimension, x) = _matches(val(sel), x)
 _matches(sel::Between, x) = (x >= first(sel)) & (x < last(sel))
 _matches(sel::At, x) = x == val(sel)
 _matches(sel::Colon, x) = true
 _matches(sel::Nothing, x) = true
+
+# Fix for https://github.com/rafaqz/DimensionalData.jl/issues/263
```
Comment (rafaqz) [inline src/coord.jl:38]: You can remove this comment.

File: src/coord.jl [hunk 2]
```diff
@@ -24,13 +24,19 @@ Coord(val::T=:) where T = Coord{T,AutoMode,NoMetadata}(val, AutoMode(), NoMetada
...
+_tozerovector(x) = zero(x)
```
Comment (rafaqz) [inline src/coord.jl:39]: `_tozero` is more accurate, and just always using map catches more types - e.g. regular `Vector` has no `zero`.

```suggestion
_tozero(xs) = map(x -> zero(x)), xs)
```

File: src/coord.jl [hunk 3]
```diff
@@ -24,13 +24,19 @@ Coord(val::T=:) where T = Coord{T,AutoMode,NoMetadata}(val, AutoMode(), NoMetada
...
+_tozerovector(x::Tuple) = map(y -> 0*y, x)
```
Comment (rafaqz) [inline src/coord.jl:40]:
```suggestion
```

File: src/coord.jl [hunk 4]
```diff
@@ -24,13 +24,19 @@ Coord(val::T=:) where T = Coord{T,AutoMode,NoMetadata}(val, AutoMode(), NoMetada
...
+@inline _reducedims(mode::CoordMode, dim::Dimension) =
+    rebuild(dim, [_tozerovector(dim.val[1])], dim.mode)
```
Comment (rafaqz) [inline src/coord.jl:42]:
```suggestion
    rebuild(dim, [_tozero(dim.val[1])], dim.mode)
```

File: test/coord.jl [hunk 5]
```diff
@@ -26,3 +27,13 @@ end
 @test index(da[Coord(:, Between(1, 3), :)], Coord) == [(1.0,1.0,1.0), (1.0,2.0,2.0)]
 
 @test bounds(da) == (((1.0, 3.0), (1.0, 4.0), (1.0, 4.0)),)
+
```
Comment (rafaqz) [inline test/coord.jl:30]: A testset with a description would help here

**Comment by rafaqz** [comment]
Thanks!

**Comment by rafaqz** [comment]
I should never merge from a phone, couldn't see the fails. Anyway, fixed. I'll bump a version.
